config/routes.rb
FLL::Application.routes.draw do
  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  get "search/search_results"
  get "static_pages/home"
  get "static_pages/about"
  get "static_pages/help"

  get "users/console"
  get "users/new"
  get "users/index"
  get "core_values/index"
  get "robot_designs/index"
  get "projects/index"

  get "search/search_results"

  match '/about', to: 'static_pages#about'
  match '/help', to: 'static_pages#help'
  match '/home', to: 'static_pages#home'

  resources :robot_designs

  resources :core_values

  resources :projects

  resources :users

  root to: 'static_pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  # :registerable,
  # :recoverable, :rememberable,
  devise :database_authenticatable,
         :trackable, :validatable
  attr_accessible :area_code, :city, :console, :first_name, :last_name, :phone_number, :role, :state, :street, :zip, :email, :password, :password_confirmation
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def console
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<% if @user.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

  <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>


<div class="row">
  <div class="span6 offset5">

    <div class="field">
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>

    <div class="field">
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>

    <div class="field">
      <%= f.label :email %>
      <%= f.text_field :email%>
    </div>

    <% if signed_in? && current_user.role == "Admin" %>
    <div class="field">
      <%= f.label :role %>
      <label class="radio inline">
        <%= f.radio_button :role, 'Admin' %> 
        <%= label :role_admin, 'Admin' %>
      </label>
      <label class="radio inline">
        <%= f.radio_button :role, 'Judge' %>
        <%= label :role_judge, 'Judge' %>
      </label>
    </div>
    <% end %>

    <div class="field">
      <%= f.label :street %>
      <%= f.text_field :street %>
    </div>

    <div class="field">
      <%= f.label :city %>
      <%= f.text_field :city %>
    </div>

    <div class="field">
      <%= f.label :zip %>
      <%= f.text_field :zip %>
    </div>

    <div class="field">
      <%= f.label :state %>
      <%= f.text_field :state %>
    </div>

    <div class="field">
      <%= f.label :area_code %>
      <%= f.text_field :area_code %>
    </div>

    <div class="field">
      <%= f.label :phone_number %>
      <%= f.text_field :phone_number %>
    </div>

    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>

    <div>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>

    <br>

    <div class="actions">
      <%= f.submit "Submit", :class => "btn btn-primary btn-large"  %>
    </div>

    <% end %>

  </div>
</div>

app/views/users/console.html.erb
<% if current_user.role == "Admin" %>
<h1>Administrator Console</h1>

<div class="buttons_row">
	<nav>
		<ul>
			<li><%= link_to 'New User', users_new_path , :class => 'button_purple'  %><div style="padding-top: 7px;">Create new user</div></li>
			<li><%= link_to 'All Users', users_path , :class => 'button_green'  %> <div style="padding-top: 7px;">View all users</div></li>
		</ul>
	</nav>
</div>

<hr class="console_hr">

<div class="buttons_row">
	<nav>
		<ul>
			<li><%= link_to 'Core Values', core_values_path , :class => 'button_blue'  %><div style="padding-top: 7px;">View all entries for core values</div></li>
			<li><%= link_to 'Robot Design', robot_designs_path , :class => 'button_red'  %> <div style="padding-top: 7px;">View all entries for robot design</div></li>
			<li><%= link_to 'Projects', projects_path , :class => 'button_orange'  %> <div style="padding-top: 7px;">View all entries for projects</div></li>
		</ul>
	</nav>
</div>

<% else %>
<h1>Judge Console</h1>

<div class="buttons_row">
	<nav>
		<ul>
			<li><%= link_to 'Core Values', core_values_path , :class => 'button_blue'  %><div style="padding-top: 7px;">View all entries for core values</div></li>
			<li><%= link_to 'Robot Design', robot_designs_path , :class => 'button_red'  %> <div style="padding-top: 7px;">View all entries for robot design</div></li>
			<li><%= link_to 'Projects', projects_path , :class => 'button_orange'  %> <div style="padding-top: 7px;">View all entries for projects</div></li>
		</ul>
	</nav>
</div>

<% end %>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% if signed_in? && current_user.role == "Admin" %>

<h1>All Users</h1>

<table class = "table table-bordered table-striped table table-hover pretty">
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Street</th>
    <th>City</th>
    <th>Zip</th>
    <th>State</th>
    <th>Area code</th>
    <th>Phone number</th>
    <th>Role</th>

    <% if signed_in? && current_user.role == "Admin" %>
    <th></th>
    <th></th>
    <th></th>
    <% end %>

</tr>

<% @users.each do |user| %>
<tr>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.street %></td>
    <td><%= user.city %></td>
    <td><%= user.zip %></td>
    <td><%= user.state %></td>
    <td><%= user.area_code %></td>
    <td><%= user.phone_number %></td>
    <td><%= user.role %></td>

    <% if signed_in? && current_user.role == "Admin" %>
    <td><%= link_to 'Show', user, :class => 'btn btn-mini btn-primary' %></td>
    <td><%= link_to 'Edit', edit_user_path(user), :class => 'btn btn-mini' %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %></td>
    <% end %>

</tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

<% else %>

<h2>Hold on ! <br><br> You don't have access to this page</h2>

<% end %>

app/views/users/new.html.erb
<% if signed_in? && current_user.role == "Admin" %>

<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

<% else %>

<h2>Hold on ! <br><br> You don't have access to this page</h2>

<% end %>

app/views/users/show.html.erb
<% if (signed_in? && current_user.role == "Admin") || (current_user.email == @user.email) %>

<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>

<p>
  <b>Street:</b>
  <%= @user.street %>
</p>

<p>
  <b>City:</b>
  <%= @user.city %>
</p>

<p>
  <b>Zip:</b>
  <%= @user.zip %>
</p>

<p>
  <b>State:</b>
  <%= @user.state %>
</p>

<p>
  <b>Area code:</b>
  <%= @user.area_code %>
</p>

<p>
  <b>Phone number:</b>
  <%= @user.phone_number %>
</p>

<p>
  <b>Role:</b>
  <%= @user.role %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

<% else %>

<h2>You can't view others profile !</h2>

<% end %>