config/routes.rb
FLL::Application.routes.draw do
  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  get "search/search_results"
  get "static_pages/home"
  get "static_pages/about"
  get "static_pages/help"

  get "users/console"
  get "users/new"
  get "users/index"
  get "core_values/index"
  get "robot_designs/index"
  get "projects/index"

  get "search/search_results"

  match '/about', to: 'static_pages#about'
  match '/help', to: 'static_pages#help'
  match '/home', to: 'static_pages#home'

  resources :robot_designs

  resources :core_values

  resources :projects

  resources :users

  root to: 'static_pages#home'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<center><%= link_to "Home ", root_path %> | <%= link_to " About", about_path %></center>

	<center>© 2013 Christopher Cruz & Muhammad Naviwala. All rights reserved </center>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<a href = "/home"><%= image_tag "/sslogo.png"%></a>

		<ul class="nav pull-right">

			<!-- search from -->
			<%= form_tag search_search_results_path, :method => 'get', :class => "navbar-search pull-left" do %>
			<%= text_field_tag :search, params[:search], :placeholder => "Search by team number...", :class =>"input-large search-query" %>
			<% end %>
			<!-- search from -->

			<li><%= link_to "Home", home_path %></li>
			<li><%= link_to "About", about_path %></li>

			<% if user_signed_in? %>
			<li><%= link_to "Console", users_console_path %></li>

			<li id="fat-menu" class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">My Account<b class="caret"></b>
				</a>
				<ul class="dropdown-menu">
					<li><%= link_to "Edit Account", edit_user_path(current_user) %></li>
					<li class="divider"></li>
					<li><%= link_to "Sign out", destroy_user_session_path %></li>
				</ul>
			</li>

			<% else %>
			<li><%= link_to "Sign in", new_user_session_path %></li>
			<% end %>

		</ul>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>FLL</title>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/header' %>

	<% flash.each do |key, value| %>
	<div class="alert alert-<%= key %>"><%= value %></div>
	<% end %>


	<%= yield %>
	

	<%= render 'layouts/footer' %>

</body>
</html>